import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { transform, type Config as SvgrConfig } from "@svgr/core";
import jsx from "@svgr/plugin-jsx";
import { optimize } from "svgo";

const ICON_FILE = /^[a-z][a-z0-9]*(?:-[a-z0-9]+)*\.svg$/;
const SOURCE_DIRECTORY = path.join(process.cwd(), "src/ui/icons/source");
const OUTPUT_DIRECTORY = path.join(process.cwd(), "src/ui/icons/generated");

const forbiddenElements = ["filter", "foreignObject", "image", "mask", "script", "style"];
const ignoredPaints = new Set(["none", "currentcolor"]);

export function iconComponentName(filename: string) {
  const basename = filename.replace(/\.svg$/, "");
  return `${basename.split("-").map((part) => part[0].toUpperCase() + part.slice(1)).join("")}Icon`;
}

export function prepareSvgSource(filename: string, source: string) {
  if (!ICON_FILE.test(filename)) {
    throw new Error(`${filename}: use a lowercase kebab-case filename such as tailored-cv.svg.`);
  }
  if (!/\bviewBox=["']0 0 24 24["']/.test(source)) {
    throw new Error(`${filename}: expected viewBox="0 0 24 24".`);
  }
  if (/\bstyle\s*=/.test(source)) {
    throw new Error(`${filename}: inline style attributes are not supported; use SVG presentation attributes.`);
  }
  for (const element of forbiddenElements) {
    if (new RegExp(`<${element}\\b`, "i").test(source)) {
      throw new Error(`${filename}: <${element}> is not allowed in interface icons.`);
    }
  }

  const paintPattern = /\b(fill|stroke)=["']([^"']+)["']/gi;
  const paints = [...source.matchAll(paintPattern)]
    .map((match) => match[2].trim())
    .filter((paint) => !ignoredPaints.has(paint.toLowerCase()));
  const uniquePaints = new Set(paints.map((paint) => paint.toLowerCase()));
  if (uniquePaints.size > 1) {
    throw new Error(`${filename}: found multiple colors (${[...uniquePaints].join(", ")}); app icons must be monochrome.`);
  }

  return source.replace(paintPattern, (attribute, property: string, paint: string) => {
    return ignoredPaints.has(paint.trim().toLowerCase()) ? attribute : `${property}="currentColor"`;
  });
}

type SvgrTemplate = NonNullable<SvgrConfig["template"]>;

function componentTemplate(variables: Parameters<SvgrTemplate>[0], { tpl }: Parameters<SvgrTemplate>[1]) {
  return tpl`
    import type { IconProps } from "../icon-types";

    export function ${variables.componentName}({ size = 24, title, ...props }: IconProps) {
      return ${variables.jsx};
    }
  `;
}

async function compileIcon(filename: string) {
  const componentName = iconComponentName(filename);
  const raw = await readFile(path.join(SOURCE_DIRECTORY, filename), "utf8");
  const prepared = prepareSvgSource(filename, raw);
  const optimized = optimize(prepared, {
    multipass: true,
    plugins: [
      "preset-default",
      "removeDimensions",
      { name: "removeAttrs", params: { attrs: "data-name" } },
    ],
  });
  const code = await transform(optimized.data, {
    expandProps: "end",
    jsxRuntime: "automatic",
    svgProps: {
      "aria-hidden": "{title ? undefined : true}",
      "aria-label": "{title}",
      "data-icon": filename.replace(/\.svg$/, ""),
      focusable: "false",
      height: "{size}",
      role: "{title ? `img` : undefined}",
      width: "{size}",
    },
    template: componentTemplate,
    typescript: true,
    plugins: [jsx],
  }, { componentName });
  return { componentName, filename, code };
}

export async function generateIcons() {
  const filenames = (await readdir(SOURCE_DIRECTORY)).filter((filename) => filename.endsWith(".svg")).sort();
  if (filenames.length === 0) throw new Error("No SVG files found in src/ui/icons/source.");
  const icons = await Promise.all(filenames.map(compileIcon));
  await rm(OUTPUT_DIRECTORY, { force: true, recursive: true });
  await mkdir(OUTPUT_DIRECTORY, { recursive: true });
  await Promise.all(icons.map(({ filename, code }) => writeFile(
    path.join(OUTPUT_DIRECTORY, filename.replace(/\.svg$/, ".tsx")),
    `/* Generated by bun run icons:generate. Do not edit directly. */\n${code}\n`,
  )));

  const exports = icons.map(({ componentName, filename }) =>
    `export { ${componentName} } from "./generated/${filename.replace(/\.svg$/, "")}";`).join("\n");
  await writeFile(path.join(SOURCE_DIRECTORY, "../index.ts"), `/* Generated by bun run icons:generate. */\n${exports}\n`);

  const imports = icons.map(({ componentName, filename }) =>
    `import { ${componentName} } from "./generated/${filename.replace(/\.svg$/, "")}";`).join("\n");
  const entries = icons.map(({ componentName, filename }) =>
    `  { name: "${filename.replace(/\.svg$/, "")}", Icon: ${componentName} },`).join("\n");
  await writeFile(path.join(SOURCE_DIRECTORY, "../catalog.ts"), `/* Generated by bun run icons:generate. */\n${imports}\n\nexport const customIconCatalog = [\n${entries}\n] as const;\n`);
  return icons.length;
}

if (import.meta.main) {
  const count = await generateIcons();
  console.log(`Generated ${count} custom icon${count === 1 ? "" : "s"}.`);
}
