/* Generated by bun run icons:generate. */
import { DocumentSparklesIcon } from "./generated/document-sparkles";

export const customIconCatalog = [
  { name: "document-sparkles", Icon: DocumentSparklesIcon },
] as const;
